name: Deploy JSON Server

on:
  push:
    branches: [ "main", "master" ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      
      - name: Install JSON Server
        run: npm install -g json-server
      
      - name: Start JSON Server
        run: npx json-server --watch db.json --port 8080 --host 0.0.0.0
